//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int AlbumId { get; set; }
        [Display(Name = "Album Title")]
        [Required(ErrorMessage = "An Album Title is required")]
        public string AlbumName { get; set; }
        [Display(Name = "Artist")]
        [Required(ErrorMessage = "An Artist is required")]
        public Nullable<int> ArtistId { get; set; }

        [Display(Name = "Track No.")]
        public Nullable<int> TrackNo { get; set; }

        public string Description { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Genre { get; set; }
    
        public virtual Artist Artist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
