//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.Category = new HashSet<Category>();
        }
    
        public int AlbumId { get; set; }
        [Display(Name ="Name")]
        public string AlbumName { get; set; }
        [Display(Name = "Track No.")]
        public Nullable<int> TrackNo { get; set; }
        public string Description { get; set; }
        [Display(Name = "Release Date")]
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Genre { get; set; }
        public Nullable<int> ArtistId { get; set; }
    
        public virtual Artist Artist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Category { get; set; }
    }
}
